// flow-typed signature: d760953a95f566a637479963a6448058
// flow-typed version: <<STUB>>/fast-xml-parser_v^3.12.11/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fast-xml-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fast-xml-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fast-xml-parser/cli' {
  declare module.exports: any;
}

declare module 'fast-xml-parser/src/json2xml' {
  declare module.exports: any;
}

declare module 'fast-xml-parser/src/nimndata' {
  declare module.exports: any;
}

declare module 'fast-xml-parser/src/node2json_str' {
  declare module.exports: any;
}

declare module 'fast-xml-parser/src/node2json' {
  declare module.exports: any;
}

declare module 'fast-xml-parser/src/parser' {
  declare module.exports: any;
}

declare module 'fast-xml-parser/src/read' {
  declare module.exports: any;
}

declare module 'fast-xml-parser/src/util' {
  declare module.exports: any;
}

declare module 'fast-xml-parser/src/validator' {
  declare module.exports: any;
}

declare module 'fast-xml-parser/src/xmlNode' {
  declare module.exports: any;
}

declare module 'fast-xml-parser/src/xmlstr2xmlnode' {
  declare module.exports: any;
}

declare module 'fast-xml-parser/tasks/postinstall' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fast-xml-parser/cli.js' {
  declare module.exports: $Exports<'fast-xml-parser/cli'>;
}
declare module 'fast-xml-parser/src/json2xml.js' {
  declare module.exports: $Exports<'fast-xml-parser/src/json2xml'>;
}
declare module 'fast-xml-parser/src/nimndata.js' {
  declare module.exports: $Exports<'fast-xml-parser/src/nimndata'>;
}
declare module 'fast-xml-parser/src/node2json_str.js' {
  declare module.exports: $Exports<'fast-xml-parser/src/node2json_str'>;
}
declare module 'fast-xml-parser/src/node2json.js' {
  declare module.exports: $Exports<'fast-xml-parser/src/node2json'>;
}
declare module 'fast-xml-parser/src/parser.js' {
  declare module.exports: $Exports<'fast-xml-parser/src/parser'>;
}
declare module 'fast-xml-parser/src/read.js' {
  declare module.exports: $Exports<'fast-xml-parser/src/read'>;
}
declare module 'fast-xml-parser/src/util.js' {
  declare module.exports: $Exports<'fast-xml-parser/src/util'>;
}
declare module 'fast-xml-parser/src/validator.js' {
  declare module.exports: $Exports<'fast-xml-parser/src/validator'>;
}
declare module 'fast-xml-parser/src/xmlNode.js' {
  declare module.exports: $Exports<'fast-xml-parser/src/xmlNode'>;
}
declare module 'fast-xml-parser/src/xmlstr2xmlnode.js' {
  declare module.exports: $Exports<'fast-xml-parser/src/xmlstr2xmlnode'>;
}
declare module 'fast-xml-parser/tasks/postinstall.js' {
  declare module.exports: $Exports<'fast-xml-parser/tasks/postinstall'>;
}
