// flow-typed signature: c54b411d50eaba47084489cf7737191e
// flow-typed version: <<STUB>>/yauzl_v^2.10.0/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yauzl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'yauzl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'yauzl/index' {
  declare module.exports: $Exports<'yauzl'>;
}
declare module 'yauzl/index.js' {
  declare module.exports: $Exports<'yauzl'>;
}
